// Bundle the ES-module app into one self-contained HTML file.
//
//   node tools/build.mjs                 -> dist/nag.html
//   node tools/build.mjs --fragment FILE -> body-only fragment (title + style + markup + script)
//
// The app keeps to two module forms on purpose so this stays dependency-free:
//   import { a, b as c } from './x.js';
//   export function|class|const|let name ... / export { a, b as c };
// Each module becomes an IIFE registered in a module map, emitted in
// dependency order, with app.js last.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'src');
const ENTRY = 'app.js';

const IMPORT_RE = /^import\s*\{([^}]*)\}\s*from\s*'\.\/([\w.-]+)';[ \t]*$/gm;
const EXPORT_DECL_RE = /^export\s+(async\s+function|function|class|const|let|var)\s+([\w$]+)/gm;
const EXPORT_LIST_RE = /^export\s*\{([^}]*)\};?[ \t]*$/gm;

function splitBindings(list) {
  return list.split(',').map((s) => s.trim()).filter(Boolean).map((s) => {
    const [orig, alias] = s.split(/\s+as\s+/).map((x) => x.trim());
    return { orig, alias: alias || orig };
  });
}

function transform(name) {
  const code = readFileSync(path.join(SRC, name), 'utf8');
  const deps = [];
  const exportsList = [];
  let body = code.replace(IMPORT_RE, (m, names, dep) => {
    deps.push(dep);
    const bindings = splitBindings(names).map((b) => (b.alias === b.orig ? b.orig : `${b.orig}: ${b.alias}`));
    return `const { ${bindings.join(', ')} } = __nag_modules[${JSON.stringify(dep)}];`;
  });
  body = body.replace(EXPORT_DECL_RE, (m, kw, id) => {
    exportsList.push(`${id}`);
    return `${kw} ${id}`;
  });
  body = body.replace(EXPORT_LIST_RE, (m, names) => {
    for (const b of splitBindings(names)) exportsList.push(b.alias === b.orig ? b.orig : `${b.alias}: ${b.orig}`);
    return '';
  });
  const leftover = body.match(/^\s*(import|export)\s/m);
  if (leftover) throw new Error(`Unsupported module syntax in ${name}: ${leftover[0].trim()}`);
  if (/import\.meta/.test(body)) throw new Error(`import.meta is not supported (${name})`);
  return { name, deps, body, exportsList };
}

function order(entry) {
  const seen = new Map();
  const out = [];
  const visiting = new Set();
  (function visit(name) {
    if (seen.has(name)) return;
    if (visiting.has(name)) throw new Error(`Circular import involving ${name}`);
    visiting.add(name);
    const mod = transform(name);
    for (const dep of mod.deps) visit(dep);
    visiting.delete(name);
    seen.set(name, mod);
    out.push(mod);
  })(entry);
  return out;
}

export function bundleScript() {
  const modules = order(ENTRY);
  const parts = ['"use strict";', 'const __nag_modules = Object.create(null);'];
  for (const mod of modules) {
    parts.push(`// ---- src/${mod.name}`);
    parts.push(`__nag_modules[${JSON.stringify(mod.name)}] = (() => {\n${mod.body}\nreturn { ${mod.exportsList.join(', ')} };\n})();`);
  }
  return parts.join('\n');
}

function dataUri(file, mime) {
  return `data:${mime};base64,${readFileSync(path.join(ROOT, file)).toString('base64')}`;
}

export function buildHtml({ fragment = false } = {}) {
  const html = readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  const css = readFileSync(path.join(ROOT, 'style.css'), 'utf8');
  const script = `window.NAG_SINGLE_FILE = true;${fragment ? ' window.NAG_AUTO_DEMO = true;' : ''}\n${bundleScript()}`;
  const banner = '<!-- Generated by tools/build.mjs from index.html, style.css and src/. Do not edit by hand. -->';

  if (fragment) {
    const body = html.slice(html.indexOf('<body>') + '<body>'.length, html.lastIndexOf('</body>'))
      .replace(/<script type="module" src="src\/app\.js"><\/script>/, '');
    return `${banner}\n<title>Nag</title>\n<style>\n${css}\n</style>\n${body}\n<script>\n${script}\n</script>\n`;
  }

  let out = html
    .replace('<link rel="stylesheet" href="style.css">', `<style>\n${css}\n</style>`)
    .replace('<link rel="manifest" href="manifest.webmanifest">\n', '')
    .replace('<link rel="icon" href="icon.svg" type="image/svg+xml">', `<link rel="icon" href="${dataUri('icon.svg', 'image/svg+xml')}" type="image/svg+xml">`)
    .replace('<script type="module" src="src/app.js"></script>', `<script>\n${script}\n</script>`);
  out = out.replace('<!DOCTYPE html>', `<!DOCTYPE html>\n${banner}`);
  return out;
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const args = process.argv.slice(2);
  const fragmentIdx = args.indexOf('--fragment');
  if (fragmentIdx >= 0) {
    const target = path.resolve(args[fragmentIdx + 1]);
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, buildHtml({ fragment: true }));
    console.log(`wrote ${target}`);
  } else {
    const target = path.join(ROOT, 'dist', 'nag.html');
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, buildHtml());
    console.log(`wrote ${path.relative(ROOT, target)} (${Math.round(readFileSync(target).length / 1024)} KB)`);
  }
}
